"use client"
import { useState, useRef, useEffect } from "react"

interface Message { role: "user" | "ai"; text: string }

// Rule-based fallback — answers common questions from context data
function answerLocally(question: string, ticker: string, ctx: any): string {
  const q = question.toLowerCase()
  const price = ctx.current_price
  const forecast = ctx.forecast_price
  const verdict = ctx.scores?.verdict
  const rsi = ctx.technicals?.rsi
  const trend = ctx.technicals?.trend
  const pe = ctx.fundamentals?.pe_ratio
  const changePct = price && forecast ? (((forecast - price) / price) * 100).toFixed(1) : null

  if (q.includes("buy") || q.includes("should i")) {
    return `Based on the analysis, ${ticker} has an overall verdict of ${verdict ?? "HOLD"}. Technical score is ${ctx.scores?.technical ?? "N/A"}/10 and fundamental score is ${ctx.scores?.fundamental ?? "N/A"}/10. This is not financial advice — always do your own research.`
  }
  if (q.includes("risk")) {
    return `${ticker} is currently ${trend ?? "trending sideways"} with RSI at ${rsi ?? "N/A"}. ${rsi > 70 ? "RSI above 70 suggests overbought conditions — elevated short-term risk." : rsi < 30 ? "RSI below 30 suggests oversold conditions — potential reversal risk." : "RSI is in neutral territory."}`
  }
  if (q.includes("forecast") || q.includes("predict") || q.includes("target")) {
    return changePct
      ? `The 7-day forecast for ${ticker} is $${forecast} (${changePct}% from current $${price}). This is generated by a ${ctx.model ?? "Prophet"} model trained on historical price data.`
      : `Forecast data is not available for ${ticker} at this time.`
  }
  if (q.includes("trend") || q.includes("momentum")) {
    return `${ticker} is currently ${trend ?? "in a neutral trend"}. MACD signal is ${ctx.technicals?.macd_signal ?? "N/A"} and RSI is ${rsi ?? "N/A"}.`
  }
  if (q.includes("p/e") || q.includes("valuation") || q.includes("fundamental")) {
    return pe
      ? `${ticker} has a P/E ratio of ${pe}. Revenue growth is ${ctx.fundamentals?.revenue_growth ?? "N/A"}%. Sector: ${ctx.fundamentals?.sector ?? "N/A"}.`
      : `Fundamental data is not available for ${ticker}.`
  }
  return `${ticker} is currently priced at $${price ?? "N/A"} with a 7-day forecast of $${forecast ?? "N/A"}. Overall verdict: ${verdict ?? "N/A"}. Ask me about risk, trend, valuation, or whether to buy.`
}

export default function AIChat({ ticker, context }: { ticker: string; context: any }) {
  const [messages, setMessages] = useState<Message[]>([
    { role: "ai", text: `Ask me anything about ${ticker} — should you buy, what's the risk, how's the trend?` }
  ])
  const [input, setInput] = useState("")
  const [loading, setLoading] = useState(false)
  const bottomRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }) }, [messages])

  async function handleSend() {
    if (!input.trim() || loading) return
    const userMsg = input.trim()
    setInput("")
    setMessages(prev => [...prev, { role: "user", text: userMsg }])
    setLoading(true)

    try {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/analyze/${ticker}/chat`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ question: userMsg, context }),
        }
      )
      if (!res.ok) throw new Error("backend unavailable")
      const data = await res.json()
      setMessages(prev => [...prev, { role: "ai", text: data.answer || answerLocally(userMsg, ticker, context) }])
    } catch {
      // Full offline fallback — no external API needed
      setMessages(prev => [...prev, { role: "ai", text: answerLocally(userMsg, ticker, context) }])
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="border border-[#1e1e1e] p-6">
      <span className="font-mono text-[10px] text-[#9ca3af] uppercase tracking-[0.2em] block mb-4">(06) AI ASSISTANT · {ticker}</span>

      <div className="h-64 overflow-y-auto space-y-3 mb-4 pr-1">
        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
            <div className={`max-w-[80%] px-4 py-3 font-mono text-xs leading-relaxed ${
              m.role === "user"
                ? "bg-[#1e1e1e] text-[#f0ede8]"
                : "border border-[#1e1e1e] border-l-2 border-l-[#d4a847] text-[#f0ede8]"
            }`}>
              {m.text}
            </div>
          </div>
        ))}
        {loading && (
          <div className="flex justify-start">
            <div className="border border-[#1e1e1e] px-4 py-3 font-mono text-xs text-[#9ca3af]">
              <span className="animate-pulse">Analyzing...</span>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      <div className="flex gap-2">
        <input
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === "Enter" && handleSend()}
          placeholder={`Ask about ${ticker}...`}
          className="flex-1 bg-[#0a0a0a] border border-[#1e1e1e] text-[#f0ede8] font-mono text-xs px-4 py-3 focus:outline-none focus:border-[#00ff87] transition-colors"
          autoComplete="off"
        />
        <button
          onClick={handleSend}
          disabled={loading}
          className="border border-[#1e1e1e] font-mono text-xs px-4 py-3 hover:border-[#00ff87] hover:text-[#00ff87] transition-colors disabled:opacity-30"
        >
          ASK →
        </button>
      </div>
    </div>
  )
}
